Channel scan select
meshtastic/Meshtastic-Android pull request #1141
Opened 2024-07-14 23:50 UTC by Robert-0410

### I believe this is related to #953.

Implemented a new dialog that is prompted when the user scans a correct QR code. The dialog provides additional
actions they can perform such as:
- Cancel: maintains the users current channels.
- Replace: makes the scanned channels the new user channels. (What would happen before)
- Save: appends the selected channels to the users existing channels.

### Notes
- The save button will only be enabled if the sum of the current and selected channels is <= max channels.
- The user can delete channels to make space, if cancel is pressed we maintain the same channels we had before the scan.

![Screenshot_20240714-164454_Meshtastic](https://github.com/user-attachments/assets/6a9e6fca-243f-4ddf-a594-6d2d536d4d76)

2024-07-21 12:00 UTC, andrekir commented
needs a few small changes but nice work!

regarding the buttons:
> Replace: makes the scanned channels the new user channels. (What would happen before)

convention is the default action ("positive") is placed on the right side of the dialog.
> Save: appends the selected channels to the users existing channels.

ensure the dialog buttons provide clear feedback of what they do: "Save" should read "Add".

2024-07-21 12:03 UTC, andrekir requested changes

2024-07-21 12:03 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
> +) {
avoid passing ViewModels to components, instead you can simply use:

``` kotlin
fun ScannedQrCodeDialog(
    channels: AppOnlyProtos.ChannelSet, (currentChannelSet)
    incoming: AppOnlyProtos.ChannelSet, (incomingChannelSet)
    onDismiss: () -> Unit,
    onConfirm: (AppOnlyProtos.ChannelSet) -> Unit,
) {
```

2024-07-21 12:03 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
> +                                viewModel.setRequestChannelUrl(Uri.parse(scannedQR))},
`setRequestChannelUrl()` calls another dialog after this one (ie. the "old" dialog we're replacing), you can use `installSettings()` instead.

2024-07-25 19:28 UTC, Robert-0410 commented on app/src/main/java/com/geeksville/mesh/ui/ChannelFragment.kt
> +) {
Thanks, good stuff!

2024-07-25 21:28 UTC, andrekir approved these changes
well done, thanks!

2024-07-25 21:41 UTC, Robert-0410 commented
Thank you!!

2024-07-28 09:58 UTC, merged