Expanding node info cards
meshtastic/Meshtastic-Android pull request #1144
Opened 2024-07-19 21:35 UTC by jamesarich

This is a rework of the UI for NodeInfo cards to be expandable. Tapping the card now expands the view to show less pertinent details as discussed in discord, https://github.com/meshtastic/Meshtastic-Android/pull/1111#issuecomment-2197270357, and #1138 .
As part of this -  the views were reworked from a Constraint view into Rows for future readability and maintainability.

Also hides the coordinates by default as mentioned in @garthvh's comment here https://github.com/meshtastic/Meshtastic-Android/discussions/1138#discussioncomment-10046245

[Screen_recording_20240719_162800.webm](https://github.com/user-attachments/assets/b0d3a87d-7a82-442e-ba79-55759bd77f52)

![image](https://github.com/user-attachments/assets/2fb38b39-7865-4e8a-b74f-c42a7510eb3c)

2024-07-19 22:46 UTC, b8b8 commented
Can this be locked in expanded view?

2024-07-19 22:49 UTC, jamesarich commented
> Can this be locked in expanded view?

it's currently just toggle-able per card

2024-07-19 22:52 UTC, b8b8 commented
ok, can you make it lock open if we want. some of us want to see all the data all the time by just scrolling vertically instead of having to tap each node. But so far this looks great. Moving the coordinate down to expanded view but keeping all other information visible in collapsed view was the right call. now we aren't relegating important info the only the expanded view while still having lots of room for future data to not impede the look.

2024-07-19 22:59 UTC, b8b8 commented
no worries, I just would like it to be a future consideration/option.
There's been a lot of talk of hiding all the info behind separate cards, and stripping away the node info page to only the most basic info. I think the way shown here is the best solution. Not everything needs to be dumbed down.

2024-07-19 23:41 UTC, jamesarich commented
@b8b8 - added a global toggle in the filter menu

2024-07-19 23:48 UTC, b8b8 commented
THANK YOU

2024-07-20 01:04 UTC, jamesarich commented
fixed expand toggle logic, added longpress to copy gps coordinates
<img width="349" alt="image" src="https://github.com/user-attachments/assets/e0131565-2788-4591-84e3-312b538985de">

2024-07-20 01:49 UTC, jamesarich commented
added node info text selection
<img width="349" alt="image" src="https://github.com/user-attachments/assets/6abd2a17-57f5-4d30-9373-291d407c961b">

2024-07-21 12:12 UTC, andrekir commented
we no longer need `contraintlayout-compose` dependency, please remove:

https://github.com/meshtastic/Meshtastic-Android/blob/de180f2d3556a2e8338099450c2f9a4d8c9f5972/app/build.gradle#L196

2024-07-21 12:27 UTC, andrekir requested changes

2024-07-21 12:27 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +                                },
.clickable can be removed here

2024-07-21 12:27 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/SignalInfo.kt
> +        } ?: ""
I don't think this is necessary. device metrics should never be null. if it is, this makes it clear to users something is wrong.

2024-07-21 13:04 UTC, andrekir approved these changes
looks good, thanks!

2024-07-28 10:04 UTC, merged