Update MeshService.kt
meshtastic/Meshtastic-Android pull request #1157
Opened 2024-07-26 15:19 UTC by musznik

Instead of showing "unknown username", display the node ID.

Why is this important? It allows for locating the node using an online map and better tuning of the antenna over long distances, recognizing distant nodes, and distinguishing them on the list.

![Screenshot_1082](https://github.com/user-attachments/assets/5fd1b4ca-be64-4d2e-9c24-b2923b2785ac)

2024-07-26 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/Meshtastic-Android?pullRequest=1157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/Meshtastic-Android?pullRequest=1157) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/Meshtastic-Android?pullRequest=1157) it.</sub>

2024-07-26 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/Meshtastic-Android?pullRequest=1157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/Meshtastic-Android?pullRequest=1157) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/Meshtastic-Android?pullRequest=1157) it.</sub>

2024-07-26 15:26 UTC, garthvh commented
You should use the last 4 of the hex node id in the colored pull too

2024-07-26 15:30 UTC, jamesarich commented
My expanding nodeinfo card PR  #1144 _does_ display the device id, but I like the idea of it being the default fallback.

2024-07-26 20:39 UTC, musznik commented
> You should use the last 4 of the hex node id in the colored pill too

![Screenshot_1083](https://github.com/user-attachments/assets/16a0073a-9735-4297-ac93-195e28ea86ec)

suggestion implemented

2024-07-27 05:03 UTC, prokrypt commented
I think it may be better to have UNK or similar in the pill. That way it is easier to spot an unknown node on the map, and makes it possible to be searched/filtered. If more info on an UNK node is needed when looking at the map, a single tap is all it takes to show the whole nodeid.

2024-07-27 13:53 UTC, thebentern commented
> I think it may be better to have UNK or similar in the pill. That way it is easier to spot an unknown node on the map, and makes it possible to be searched/filtered. If more info on an UNK node is needed when looking at the map, a single tap is all it takes to show the whole nodeid.

I disagree entirely. UNK provides zero helpful information. It's an all-caps acronym that is does not translate well and is not immediately apparent to all users. Whereas the last 4 hex gives you actual relevant information about the node. We can add filters for unknown nodes without having that useless string in the pill.

2024-07-27 13:54 UTC, thebentern approved these changes
Love it! Great work!

2024-07-27 14:07 UTC, prokrypt commented
> > I think it may be better to have UNK or similar in the pill. That way it is easier to spot an unknown node on the map, and makes it possible to be searched/filtered. If more info on an UNK node is needed when looking at the map, a single tap is all it takes to show the whole nodeid.
> 
> I disagree entirely. UNK provides zero helpful information. It's an all-caps acronym that is does not translate well and is not immediately apparent to all users. Whereas the last 4 hex gives you actual relevant information about the node. We can add filters for unknown nodes without having that useless string in the pill.

But the downside with the current shortname is that there is no way on the map to differentiate an unknown node and one with nodeinfo, and there is a high chance the shortname will change when nodeinfo is received.

2024-07-27 14:31 UTC, thebentern commented
> But the downside with the current shortname is that there is no way on the map to differentiate an unknown node and one with nodeinfo, and there is a high chance the shortname will change when nodeinfo is received.

A NodeInfo (User) will either arrive eventually or it won't. Knowing whether a node is "unknown" does not give the user any actionable path.

2024-07-27 14:42 UTC, prokrypt commented
> A NodeInfo (User) will either arrive eventually or it won't. Knowing whether a node is "unknown" does not give the user any actionable path.
If an auto generated short name is displayed, a user is more likely to use it to search on an online map and likely not be able to find it. Isn't it better to make it obvious there is no nodeinfo so a user will search using the nodeid?

2024-07-27 15:04 UTC, garthvh commented
> > A NodeInfo (User) will either arrive eventually or it won't. Knowing whether a node is "unknown" does not give the user any actionable path.
> 
> If an auto generated short name is displayed, a user is more likely to use it to search on an online map and likely not be able to find it. Isn't it better to make it obvious there is no nodeinfo and force a user to search using the nodeid?
> 
> Maybe another method would be to have a ! in the short name too, if 5 characters is possible.

A year in not a single user has requested the return of ??? On iOS instead of relevant data I think you are a real edge case here.

2024-07-27 20:56 UTC, prokrypt commented
> A year in not a single user has requested the return of ??? On iOS instead of relevant data I think you are a real edge case here.

I just feel like a known (or rather, UNKnown or ???) is replaced with an unknown (a generated shortname that may change at any time). Currently, it is difficult to tell if a node in chat has nodeinfo or not if their shortname is in hex format. If you press on their shortname, it just jumps to the nodelist unless you enable "Include unknown".

2024-07-27 22:04 UTC, garthvh commented
> > A year in not a single user has requested the return of ??? On iOS instead of relevant data I think you are a real edge case here.
> 
> I just feel like a known (or rather, UNKnown or ???) is replaced with an unknown (a generated shortname that may change at any time). Currently, it is difficult to tell if a node in chat has nodeinfo or not if their shortname is in hex format. If you press on a shortname with no nodeinfo, it just jumps to the nodelist unless you enable "Include unknown".

This is a seperate issue and can be determined from the lack of hardware model data 
![IMG_2964](https://github.com/user-attachments/assets/3ff8fcb1-a75c-43dc-a881-aa5644bcff4c)

2024-07-28 11:20 UTC, andrekir requested changes

2024-07-28 11:20 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/service/MeshService.kt
> +        val shortName = if (defaultId.length >= 4) {
nodeNumToDefaultId() returns a fixed length of 9 characters, so this is always true and can be removed

2024-07-28 11:20 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/service/MeshService.kt
> +            defaultId.takeLast(4)
use .takeLast(n = 4) to fix the lint error

2024-08-18 17:53 UTC, closed without merging