feat: Add role to NodeInfo
meshtastic/Meshtastic-Android pull request #1174
Opened 2024-08-01 02:58 UTC by jamesarich

This commit adds a new field called `role` to the `NodeInfo` class. The `role` field is of
 type `DeviceConfig.Role` and is used to store the role of the node in the mesh network.

The following changes were made to implement this feature:

- Added `role` field to `NodeInfo` class.
- Updated `MeshUser` class to include `role` field.
- Updated `NodeInfoDaoTest` to include `role` field in test data.
- Updated `PreviewParameterProviders` to include `role` field in preview data.
- Updated `MeshService` to include `role` field in default node info.
- Updated UI to display the node role.

@andrekir - I found the `role` defined in the proto here https://buf.build/meshtastic/protobufs/docs/main:meshtastic#meshtastic.User and added it to our local model. Let me know if there's a better/more preferred way to add a field from a proto.

2024-08-03 12:12 UTC, andrekir requested changes

2024-08-03 12:12 UTC, andrekir commented on app/schemas/com.geeksville.mesh.database.MeshtasticDatabase/8.json
> +        "createSql": "CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`num` INTEGER NOT NULL, `snr` REAL NOT NULL, `rssi` INTEGER NOT NULL, `lastHeard` INTEGER NOT NULL, `channel` INTEGER NOT NULL, `hops
we never change an existing schema directly. this can cause data loss and crashes. use Room auto migration to add a new schema.

2024-08-03 12:12 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +    val role: DeviceConfig.Role
using protobuf enums for types (like hwModel) is problematic, instead use `Int` to work with the "_VALUE" suffix (e.g., CLIENT -> CLIENT_VALUE) and role.number

then you can tag "= 0" as default value (CLIENT) so we don't need any extra handling elsewhere like in testing

```kotlin
data class MeshUser(
    val id: String,
    val longName: String,
    val shortName: String,
    val hwModel: MeshProtos.HardwareModel,
    val isLicensed: Boolean = false,
    val role: Int = 0, // ConfigProtos.Config.DeviceConfig.Role.CLIENT_VALUE
) : Parcelable {
```

2024-08-04 14:53 UTC, andrekir commented
please follow the [official docs](https://developer.android.com/training/data-storage/room/migrating-db-versions) for details. check the database git history for examples. this can cause big problems if not done right.

2024-08-04 15:08 UTC, jamesarich commented
> please follow the [official docs](https://developer.android.com/training/data-storage/room/migrating-db-versions) for details. check the database git history for examples. this can cause big problems if not done right.

Gotcha - I'll move this to draft and do a little research. Thanks for reviewing.

2024-08-04 16:28 UTC, jamesarich commented
@andrekir - I think I got it sorted, the Automigration was failing due to expecting a nullable `role`.  Want to give it another look?

2024-08-06 10:37 UTC, andrekir commented
you can define a default value for a column by using the annotation @ColumnInfo(defaultValue = "...")
```kotlin
@ColumnInfo(defaultValue = "0")
val role: Int = 0,
```

2024-08-07 22:45 UTC, jamesarich commented
@andrekir another round? :sweat:

2024-08-08 13:34 UTC, andrekir commented
that should do it. I'll get back to it soon. 👍

2024-08-10 11:02 UTC, andrekir approved these changes

2024-08-10 11:17 UTC, merged