feat: Add position precision indicator to map
meshtastic/Meshtastic-Android pull request #1177
Opened 2024-08-02 16:35 UTC by jamesarich

This commit adds a visual indicator to the map that shows the precision of a node's position. The indicator is
 a circle around the node's marker, and the size of the circle corresponds to the precision of the position.

The precision is determined by the `precisionBits` field in the node's position data. The higher the `precisionBits` value, the more precise the position.

This feature helps users to
 understand the accuracy of the position data displayed on the map.

closes #893

2024-08-03 12:59 UTC, andrekir requested changes

2024-08-03 12:59 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
> +                            mapView?.context?.let { context ->
onNodesChanged is a `MapView` extension function. you have access to it with `this@onNodesChanged`

2024-08-03 12:59 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
> +                                    ContextCompat.getColor(context, R.color.colorPrimary)
`Context` calls can be relatively expensive, instead of calculating `colorPrimary` for every node, do it once at the top and reuse it.

2024-08-03 13:52 UTC, jamesarich commented on app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
> +                                    ContextCompat.getColor(context, R.color.colorPrimary)
not even needed if defined above

2024-08-03 13:59 UTC, andrekir requested changes

2024-08-03 13:59 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
> +                            val polygon = Polygon(this.mapView)
```kotlin
val polygon = Polygon(this@onNodesChanged)
```

2024-08-03 13:59 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
> +class MarkerWithLabel(val mapView: MapView?, label: String, emoji: String? = null) : Marker(mapView) {
then making mapView public is unnecessary

2024-08-03 15:44 UTC, jamesarich commented on app/src/main/java/com/geeksville/mesh/ui/map/MapFragment.kt
> +                            val polygon = Polygon(this.mapView)
🤦 gotcha

2024-08-03 16:08 UTC, andrekir approved these changes
thanks!

2024-08-03 16:08 UTC, merged

2024-08-15 18:30 UTC, prokrypt commented
https://github.com/user-attachments/assets/2dcf04da-e312-4a4a-a05e-658c3b1fc048

also, sometimes the circles are drawn over the node markers and eating taps 🫠

2024-08-16 01:22 UTC, jamesarich commented
> screen-20240815-112648.mp4 
> also, sometimes the circles are drawn over the node markers and eating taps 🫠

#1190 is a rework - should help :crossed_fingers: