Fix: Colored transparent precision circles around nodes on map
meshtastic/Meshtastic-Android pull request #1190
Opened 2024-08-09 19:26 UTC by jamesarich

This updates precision circles around nodes on the map to better visually represent the accuracy of their positions. The circles are now colored according to the node's color and are now more transparent.

This also hoists the adding of the precision circle to the overlay, so it can be managed alongside markers. This fixes the redraw on zoom issue that users were experiencing.

2024-08-10 01:13 UTC, andrekir commented
there are other Polygon() instances in the code, and managing them separately will be very complicated. to avoid that you can simply move the polygon into `MarkerWithLabel`.

https://github.com/meshtastic/Meshtastic-Android/blob/6d01fb4bc41b072903c4a2470bd78362b9474f3a/app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt#L60-L69

`org.osmdroid.views.overlay.Polygon` also has a draw method:

```kotlin
class MarkerWithLabel(mapView: MapView?, label: String, emoji: String? = null) : Marker(mapView) {
(...)

    private var precisionBits: Int? = null

    fun setPrecisionBits(bits: Int) {
        precisionBits = bits
    }

(...)
    override fun draw(c: Canvas, osmv: MapView?, shadow: Boolean) {
    (...)
        precisionBits?.let {
            val polygon = Polygon(osmv).apply {
                points = Polygon.pointsAsCircle(
                    position,
                    bitsToMeters(it)
                )
                fillPaint.color = Color.RED
                fillPaint.alpha = 64
                outlinePaint.color = Color.RED
            }
            polygon.draw(c, osmv, false)
        }
    }
```

2024-08-10 16:12 UTC, jamesarich commented
Good catch - don't want to nuke those other Polygons, makes it simpler to just add them to the marker canvas.

2024-08-18 09:47 UTC, andrekir requested changes

2024-08-18 09:47 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
> +        when (precisionBits) {
without a getter this variable is static and will always point to null

2024-08-18 09:47 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/model/map/MarkerWithLabel.kt
> +        nodeColor = colors.first
= colors.second

2024-08-20 20:04 UTC, andrekir approved these changes

2024-08-20 20:04 UTC, merged