feat: add support for Device Hardware json and svg graphics
meshtastic/Meshtastic-Android pull request #1449
Opened 2024-12-06 02:37 UTC by jamesarich

Adds device_hardware.json, DeviceHardware model, svg device graphics, and convenience methods to parse the json and map it to DeviceHardware model and image resource.

Allows for better hardware device display names, graphics, and indication of support.

![image](https://github.com/user-attachments/assets/bdd5aa42-c766-4ff1-84c1-70fc42a06631)

2024-12-06 10:05 UTC, andrekir commented
Please move the images from the detail section to a header at the top of the screen. The header should place the image in focus without overwhelming the rest of the screen, so it also needs to work well with both horizontal and vertical images. Maybe use a complementary background with the hardware name under the image.

2024-12-06 12:58 UTC, jamesarich commented
@andrekir - i moved the relevant device info up to a new `Device` section above the `Details`. I also restricted the device image size and gave it a circular background with the node color (alpha 50%).

2024-12-07 12:35 UTC, andrekir requested changes

2024-12-07 12:35 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/model/DeviceHardware.kt
> +        val resourceId = context.resources.getIdentifier(
this isn't working, the JSON image field uses dash (-) and the filenames have underscores (_).

getIdentifier() reflection is very unreliable, use `when` instead.

2024-12-07 12:35 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/NodeDetail.kt
> +        DeviceHardware.getDeviceHardwareFromHardwareModel(context, node.user.hwModel)
this can move to the ViewModel and use app context. also needs some exception handling.

2024-12-07 14:55 UTC, jamesarich commented
@andrekir - I moved the DeviceHardware and image res functions to MetricsViewModel, and added some State variables.

The DeviceHardware json parsing now has exception handling and is cached in the model to avoid expensive rereads.

I also updated the image res function to use `when` mapping from HardwareModel enum to Drawable resource id. This function will need to be updated when new images are added.

2024-12-10 14:57 UTC, andrekir approved these changes

2024-12-10 15:02 UTC, merged