Bluetooth reconnect fix android15
meshtastic/Meshtastic-Android pull request #1463
Opened 2024-12-13 22:40 UTC by tavdog

This pull fixes two issues.
1.  The necessity to click None before manually selecting a reconnect from the BT device popup.
2.  The prolonged disconnection non-reconnect behaviour is fixed by trapping BT disconnect code 147 and calling lostConnection() function.  This sets up a reconnect attempt loop every 30 seconds. This might be power draining. Could add a user preference somewhere to do this or not. Built apk is available here for testing : https://wildc.net/tmp/meshtastic-fdroid-debug.apk

2024-12-13 22:46 UTC, Franselbaer commented
Thank you. Perhaps a on/off button and/or reconnect timeout set (30 sec - 300 sec) would be a good idea. Great work.

2024-12-14 04:36 UTC, tavdog commented
I just tested these changes on  a Pixel 3 - Android 12 - API 31 and it doesn't effect its ability to reconnect.
I'll be doing a battery test tonight to see if the new changes drain the battery noticeably.

2024-12-15 10:46 UTC, andrekir requested changes

2024-12-15 10:46 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/repository/radio/RadioInterfaceService.kt
> +        return if (getBondedDeviceAddress() == address && isStarted && isConnected) {
This is intended behavior. We specifically track `isStarted` just for this call. Please revert this change, and it should be good to merge.

2024-12-15 11:05 UTC, andrekir approved these changes

2024-12-18 11:14 UTC, merged