Update strings.xml
meshtastic/Meshtastic-Android pull request #338
Opened 2022-01-05 07:53 UTC by slavino

Update to meet recent App state

2022-01-05 12:48 UTC, andrekir commented
thank you. added a small review note for channel description strings. up to you to consider any changes or submit as is.

2022-01-05 13:43 UTC, slavino commented
I don't see any review notes. Where can I find those?

2022-01-05 14:06 UTC, randybb commented on app/src/main/res/values-sk/strings.xml
> +    <string name="meshtastic_service_notifications">Notifikácie zo služby  Meshtastic</string>
two spaces before Meshtastic

2022-01-05 14:06 UTC, randybb commented on app/src/main/res/values-sk/strings.xml
> +    <string name="must_update">Musíte aktualizovať aplikáciu na Google Play store (alebo z Github). Je príliš stará pre komunikáciu s touto verziou firmvéru vysielača. Viac informácií k tejto téme ná
a space before .

2022-01-05 14:10 UTC, randybb requested changes
Only two extra spaces.

2022-01-05 17:02 UTC, andrekir commented on app/src/main/res/values-sk/strings.xml
>      <string name="modem_config_very_long">Veľmi dlhá vzdialenosť (pomalý prenos dát)</string>
![Screenshot_20220105-092908](https://user-images.githubusercontent.com/48680741/148218098-d67eeb11-85b4-4615-8b60-47ced32ccf5f.jpg) ![Screenshot_20220105-085831](https://user-images.githubusercontent.com/48680741/148218134-5e09a1f6-38e0-4420-9b7c-232587596942.jpg)

`(modem_config)_short, _medium, _long & _very_long` changed recently to a very short text format "Range / Speed" because they would not fit the channel drop down menu (above).

Same format you used on the new channel strings:

<string name="modem_config_slow_short">Krátky dosah / Pomalé</string>
<string name="modem_config_slow_medium">Stredný dosah / Pomalé</string>

2022-01-07 06:18 UTC, slavino commented on app/src/main/res/values-sk/strings.xml
>      <string name="modem_config_very_long">Veľmi dlhá vzdialenosť (pomalý prenos dát)</string>
Done

2022-01-10 01:48 UTC, merged

2022-01-10 12:21 UTC, caveman99 commented
ERROR:Meshtastic-Android/app/src/main/res/values-sk/strings.xml: Resource and asset merger: Found item String/connected more than one time
FAILURE: Build failed with an exception.

the string 'connected' is indeed included twice in the XML, causing the build to bomb.

2022-01-14 03:22 UTC, geeksville commented
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-android-1-2-53-alpha/4778/1