Shows a prompt when Bluetooth is off and trying to add a device
meshtastic/Meshtastic-Android pull request #469
Opened 2022-08-23 15:54 UTC by legendgroupv2

When trying to add a Meshtastic device, the app will check if Bluetooth is turned on, if it isn't then it will display a message.

2022-08-23 20:53 UTC, andrekir requested changes
@legendgroupv2 Thanks for your contribution!
Please check my reviews 👍

2022-08-23 20:53 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/SettingsFragment.kt
> +        if (!(btAdapter.isEnabled())) {
Bluetooth state is handled via `bluetoothViewModel.enabled.value`, then `BluetoothAdapter` import can also be removed.

```suggestion
        if (bluetoothViewModel.enabled.value == false) {
```

2022-08-30 09:46 UTC, legendgroupv2 commented
Thanks for your reviews. All done :)

2022-08-30 20:26 UTC, andrekir approved these changes
thanks

2022-08-30 20:26 UTC, merged