Add option for Miles and Feet for distance
meshtastic/Meshtastic-Android pull request #651
Opened 2023-07-04 17:36 UTC by jp-bennett

2023-07-04 17:38 UTC, jp-bennett commented
There is one problem, that the current view doesn't update when the units are switched. I'm not sure the best way to trigger a refresh.

2023-07-05 10:39 UTC, andrekir requested changes

2023-07-05 10:39 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/MainActivity.kt
> +        public var prefUnits = 0
storing public variables in an Activity should be avoided

2023-07-05 10:39 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/MainActivity.kt
> +    }
this isn't needed, instead use the radio config stored in `viewModel.config.display.units`
--> DisplayConfig.DisplayUnits.METRIC_VALUE == 0
and DisplayConfig.DisplayUnits.IMPERIAL_VALUE == 1

2023-07-05 10:39 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +            prefUnits == 0 && dist > 1000 -> "%.1f km".format(dist / 1000.0)
missing dist == 1000, use >=

2023-07-05 10:39 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +            prefUnits == 1 && dist < 1609 -> "%.0f feet".format(dist.toDouble()*3.281)
convention is to use the abbreviated form 'ft' here

2023-07-05 10:39 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +            prefUnits == 1 && dist >= 1609 -> "%.1f miles".format(dist / 1609.34)
same, use 'mi' here

2023-07-05 10:53 UTC, andrekir commented
simplest way:

1. in fragments that call distanceStr() --> add `val prefUnits = model.config.display.units.number `
2. add the prefUnits argument in the fragments distanceStr() calls: distanceStr(x) --> distanceStr(x, prefUnits)
3. in NodeInfo.kt you pass the value adding a parameter to distanceStr() --> like: distanceStr(o: Nodeinfo, unit: Int = 0) ...

let me know if you need any help

2023-07-05 16:13 UTC, jp-bennett commented on app/src/main/java/com/geeksville/mesh/MainActivity.kt
> +        public var prefUnits = 0
I really struggled to find another way to store global configuration data. What is the better way to do it?

2023-07-05 19:54 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/MainActivity.kt
> +        public var prefUnits = 0
in Android always: UI -> ViewModel -> data sources

metric/imperial units is already stored in the UIState viewmodel. see my other comments. nothing should be added in MainActivity.

2023-07-06 16:45 UTC, jp-bennett commented on app/src/main/java/com/geeksville/mesh/MainActivity.kt
> +        public var prefUnits = 0
Am I understanding correctly, that `model.config.display.units.number` should already contain an int value corresponding to either `ConfigProtos.Config.DisplayConfig.DisplayUnits.METRIC_VALUE` or `ConfigProtos.Config.DisplayConfig.DisplayUnits.IMPERIAL_VALUE`? And I shouldn't have to add a menu option at all?

2023-07-06 18:04 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/MainActivity.kt
> +        public var prefUnits = 0
> Am I understanding correctly, that `model.config.display.units.number` should already contain an int value corresponding to either `ConfigProtos.Config.DisplayConfig.DisplayUnits.METRIC_VALUE` or `ConfigProtos.Config.DisplayConfig.DisplayUnits.IMPERIAL_VALUE`?

yes, `METRIC_VALUE` is 0 and `IMPERIAL_VALUE` is 1.

> And I shouldn't have to add a menu option at all?

correct

2023-07-06 19:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/Meshtastic-Android?pullRequest=651) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/Meshtastic-Android?pullRequest=651) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/Meshtastic-Android?pullRequest=651) it.</sub>

2023-07-06 19:42 UTC, jp-bennett commented
@andrekir I think that should put this in better shape. Thanks for the hand-holding.

2023-07-06 21:26 UTC, merged

2023-07-06 21:27 UTC, andrekir commented
looks good! thanks!