Honor radio's option to use Fahrenheit.
meshtastic/Meshtastic-Android pull request #658
Opened 2023-07-14 22:46 UTC by jp-bennett

Closes #599

2023-07-15 11:42 UTC, andrekir requested changes

2023-07-15 11:42 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +    }
```suggestion
    fun envMetricStr(isFahrenheit: Boolean = false): String =
        if (!isFahrenheit) envFormat("%.1f", "°C ", environmentMetrics?.temperature)
        else envFormat("%.1f", "°F ", environmentMetrics?.temperature?.times(1.8f)?.plus(32)) +
                envFormat("%.0f", "%% ", environmentMetrics?.relativeHumidity) +
                envFormat("%.1f", "hPa ", environmentMetrics?.barometricPressure) +
                envFormat("%.0f", "mΩ ", environmentMetrics?.gasResistance) +
                envFormat("%.2f", "V ", environmentMetrics?.voltage) +
                envFormat("%.1f", "mA", environmentMetrics?.current)
```

2023-07-15 11:42 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +    }
- referencing Fahrenheit in the parameter name to improve readability
- you can avoid repetition using only the temperature string inside the if/else block:

Celsius: `envFormat("%.1f", "°C ", environmentMetrics?.temperature)`
Fahrenheit: `envFormat("%.1f", "°F ", environmentMetrics?.temperature?.times(1.8f)?.plus(32))`

2023-07-15 11:42 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt
> +                holder.envMetrics.text = n.envMetricStr(model.module.telemetry.environmentDisplayFahrenheit)
make sure to check your added code follows [coding conventions](https://kotlinlang.org/docs/coding-conventions.html). to reformat the selected text In Android Studio there is the Ctrl + Alt + L hotkey.

you could also store `n.envMetricStr(model.module.telemetry.environmentDisplayFahrenheit` in a variable before the if/else block so it is only called once.

2023-07-15 13:18 UTC, jp-bennett commented
@andrekir I knew there would be some Kotlin magic I missed out on. Thanks for the suggestions, I'll test and amend the PR in a bit.

2023-07-15 15:58 UTC, jp-bennett commented
@andrekir Thanks again. I tried the .times()?.plus() construction during development, and was getting weird results. But apparently that was spurious and unrelated, as this morning it's working just fine. I think this is ready to go.

2023-07-16 08:46 UTC, merged

2023-07-16 08:47 UTC, andrekir commented
looks good. thanks!