Feature: Jump to node info from message
meshtastic/Meshtastic-Android pull request #844
Opened 2024-02-10 21:07 UTC by daviscodesbugs

I believe this fully addresses issue #778

From within a message, tapping on the node short name will navigate to the node list tab and scroll to that node. Added bonus: the node will flash a couple times to draw the users attention. Figured this is the best solution at the moment since there isn't a more in-depth node details view.

Also did a bit of refactoring around the tabs of the main menu to make simplify future changes to icons or strings in the main menu, as well as translations. Important to note that the order that the values of the MainTab enum are defined will be the order they appear in the UI.

https://github.com/meshtastic/Meshtastic-Android/assets/22112533/96410f68-a1dc-427d-8148-f21dcbe3656c

2024-02-11 10:25 UTC, andrekir requested changes
great work! added a small note for review.

2024-02-11 10:25 UTC, andrekir commented on app/src/main/res/values/strings.xml
> +    <string name="main_tab_lbl_settings">Settings</string>
can you add `translatable="false"` into these? I don't want to send them for translation just yet.

2024-02-13 13:59 UTC, daviscodesbugs commented on app/src/main/res/values/strings.xml
> +    <string name="main_tab_lbl_settings">Settings</string>
Sure thing! Made those changes.
Is there some automated process to translate those? Just wondering why they need to be marked not translatable

2024-02-13 21:31 UTC, andrekir commented on app/src/main/res/values/strings.xml
> +    <string name="main_tab_lbl_settings">Settings</string>
the plugin can be a pain, so just to be safe. but this is an exception, these names are ancient and you'll notice some variation over time.

2024-02-13 21:32 UTC, merged