Move Node info completely to Compose
meshtastic/Meshtastic-Android pull request #886
Opened 2024-02-29 15:50 UTC by daviscodesbugs

Node info is now completely in Compose

Moved over to use constraints for more dynamic layout
Added a string composing method for environment metrics that doesn't have the space baked in to each value.
Note: the feature that navigates from a chat to the node list and highlights the node will be broken. The navigation aspect works, but the blink does not. I'll have to follow up on that

- Layout adjust to accommodate wide coordinate formats
- Intelligently update node list only where information changed

Coordinates are aligned to top of signal info, but wrapped with last heard. This leaves some blank space to the side, but isn't too significant considering this should only happen on node long names that wrap
![image](https://github.com/meshtastic/Meshtastic-Android/assets/22112533/e941b8ec-fed2-4124-8811-eea98a63fcb2)

2024-02-29 19:15 UTC, andrekir requested changes
super! added some small notes for review.

2024-02-29 19:15 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +    val unknownLongName = stringResource(id = R.string.unknown_node_long_name)
there is a resource string for "unknown name" --> _R.string.unknown_username_

2024-02-29 19:15 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +    val nodeName = thatNodeInfo.user?.longName ?: unknownLongName
also suggest using `getInitials(nodeName)` instead of a resource string for unknownShortName:

```kotlin
val unknownShortName = getInitials(nodeName)
```
or directly:

```kotlin
val shortName = thatNodeInfo.user?.shortName ?: getInitials(nodeName)
```

(then using `shortName` in line 90 below)

2024-02-29 19:15 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/NodeInfo.kt
> +    }
can we remove `envMetricStr` and `envFormat` after this change?

2024-02-29 20:03 UTC, daviscodesbugs commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +    val unknownLongName = stringResource(id = R.string.unknown_node_long_name)
Yes! I did see that, but that value is "Unknown Username" and the one I added is just "Unknown" (like in the examples above) Do we want it to say "Unknown Username"?

2024-02-29 20:08 UTC, daviscodesbugs commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +    val nodeName = thatNodeInfo.user?.longName ?: unknownLongName
Oh cool! Didn't know about this method. I'll mention you in another comment on this

2024-02-29 20:33 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +    val unknownLongName = stringResource(id = R.string.unknown_node_long_name)
yeah, "Unknown Username" / _R.string.unknown_username_ is what is use elsewhere specific for unknown node longNames.

(you'll notice "node" and "user" are often used interchangeably)

2024-03-04 19:28 UTC, andrekir commented on app/src/main/java/com/geeksville/mesh/ui/NodeInfo.kt
> +    val nodeName = thatNodeInfo.user?.longName ?: unknownLongName
just checking in for an update on this one. if you add `unknown_node_short_name` as "???", please tag it translatable=false.

2024-03-07 08:38 UTC, andrekir approved these changes

2024-03-07 08:39 UTC, merged